# Title: RodriguezAlvarado-composers.yaml
# Date: 01/26/2024
# Author: Zadkiel Rodriguez Alvarado
# Description: API for searching and creating composers
# Sources: 
# https://editor.swagger.io/#/
# https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: Composer API
  version: "1.0"
paths:
  /composers:
    description: The list of composers
    get:
      summary: Returns a list of composers documents
      tags:
        - composers
      operationId: findAllComposers
      description: API for returning a list of composers from MongoDB Atlas
      responses:
        "200":
          description: Composer documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      summary: Creates a new composer
      tags:
        - composers
      operationId: createComposer
      description: API for adding new composers objects
      requestBody:
        description: Composer's information
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: User added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    description: The list of composers
    get:
      summary: Returns a composer document
      tags:
        - composers
      operationId: findComposerById
      description: API for returning a single composer object from MongoDB
      parameters:
        - name: id
          in: path
          description: The composerId requested by the user. 
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Composer document in JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception